### ISSUE TITLE
Deployment fails with "Project does not contain a Dockerfile and has not set a CNB builder, builtin builder or selected an image"

### ISSUE THREAD

**Issue by lacommu** [fly-examples/hellofly#1]
Hello,
I'm trying to experiment fly.io using this repo but I'm having issues deploying it. It fails with error : 
`Project does not contain a Dockerfile and has not set a CNB builder, builtin builder or selected an image`

Repro steps : 
- clone the project
- login to flyctl
- flyctl init 
- select Go builtin (and default answers for the rest)
- flyctl deploy

Am I missing a step ?

Thanks

**Comment by codepope** [comment]
Could you tell me what version of flyctl you are using? (`flyctl version`)

**Comment by lacommu** [comment]
I'm using 0.0.139 on Linux

**Comment by codepope** [comment]
Ah, issue found....

If you remove the .gitignore file from the project clone, it should build fine.

It was an issue that pops up with remote building when you don't have Docker installed locally.

**Comment by lacommu** [comment]
Yep that solved it ! Thanks :)
